#pragma once
class Juego
class MapaOTablero
class Mina
class Bandera
class Camuflaje
class Numero
class ContadorDeMinas
class Sospecha
class Reiniciar
class Dificultad
class Menu
class 1
class 2
class 3
class 4
class 5
class 6
class 7
class 8
class Explosion
class cronometro 

class perder 
class ganar 


Juego "1" *-- "1" Menu
Menu "1" o-- "3" Dificultad
Dificultad "1" --|> "1" MapaOTablero
Juego "1" o-- "1" MapaOTablero
MapaOTablero"1" *-- "*" Mina
MapaOTablero "1" o-- "1" ContadorDeMinas
ContadorDeMinas "1" *-- "1" Dificultad
MapaOTablero "1" *-- "*" Numero
MapaOTablero "1" o-- "1" Reiniciar
MapaOTablero "1" *-- "*" Camuflaje
MapaOTablero "1" *-- "1" cronometro
Mina "1" *-- "1" Camuflaje
Mina "1" --|> "1" Bandera
Mina "1" o-- "0,1" Sospecha
Mina "1" o-- "1..8" Numero
Mina "1" *-- "*" Explosion
Camuflaje "1" --|> "1" Bandera
Camuflaje "1" --|> "1" Sospecha
1 "1" --|> "1" Numero
2 "1" --|> "1" Numero
3 "1" --|> "1" Numero
4 "1" --|> "1" Numero
5 "1" --|> "1" Numero
6 "1" --|> "1" Numero
7 "1" --|> "1" Numero
8 "1" --|> "1" Numero

